export const GET_INGREDIENTS_CONSTRUCTOR: "GET_INGREDIENTS_CONSTRUCTOR" =
  "GET_INGREDIENTS_CONSTRUCTOR";

export const SORT_INGREDIENTS_CONSTRUCTOR: "SORT_INGREDIENTS_CONSTRUCTOR" =
  "SORT_INGREDIENTS_CONSTRUCTOR";

export const ADD_INGREDIENT_CONSTRUCTOR: "ADD_INGREDIENT_CONSTRUCTOR" =
  "ADD_INGREDIENT_CONSTRUCTOR";

export const DELETE_INGREDIENT_CONSTRUCTOR: "DELETE_INGREDIENT_CONSTRUCTOR" =
  "DELETE_INGREDIENT_CONSTRUCTOR";

export const DELETE_All_INGREDIENT_CONSTRUCTOR: "DELETE_All_INGREDIENT_CONSTRUCTOR" =
  "DELETE_All_INGREDIENT_CONSTRUCTOR";

export const ADD_BUN_CONSTRUCTOR: "ADD_BUN_CONSTRUCTOR" = "ADD_BUN_CONSTRUCTOR";
