export const GET_INGREDIENTS_CONSTRUCTOR_REQUEST = 'GET_INGREDIENTS_CONSTRUCTOR_REQUEST';
export const GET_INGREDIENTS_CONSTRUCTOR_SUCCESS = 'GET_INGREDIENTS_CONSTRUCTOR_SUCCESS';
export const GET_INGREDIENTS_CONSTRUCTOR_FAILED = 'GET_INGREDIENTS_CONSTRUCTOR_FAILED';

export const SORT_INGREDIENTS_CONSTRUCTOR = 'SORT_INGREDIENTS_CONSTRUCTOR';


export const ADD_INGREDIENT_CONSTRUCTOR_REQUEST = 'ADD_INGREDIENT_CONSTRUCTOR_REQUEST';
export const ADD_INGREDIENT_CONSTRUCTOR_SUCCESS = 'ADD_INGREDIENT_CONSTRUCTOR_SUCCESS';
export const ADD_INGREDIENT_CONSTRUCTOR_FAILED = 'ADD_INGREDIENT_CONSTRUCTOR_FAILED';

export const DELETE_INGREDIENT_CONSTRUCTOR = 'DELETE_INGREDIENT_CONSTRUCTOR';

export const ADD_BUN_CONSTRUCTOR_REQUEST = 'ADD_BUN_CONSTRUCTOR_REQUEST';
export const ADD_BUN_CONSTRUCTOR_SUCCESS = 'ADD_BUN_CONSTRUCTOR_SUCCESS';
export const ADD_BUN_CONSTRUCTOR_FAILED = 'ADD_BUN_CONSTRUCTOR_FAILED';