export const GET_ORGER_DETAILS_REQUEST = 'GET_ORGER_DETAILS_REQUEST';
export const GET_ORGER_DETAILS_SUCCESS = 'GET_ORGER_DETAILS_SUCCESS';
export const GET_ORGER_DETAILS_FAILED = 'GET_ORGER_DETAILS_FAILED';

export const DELETE_ORGER_DETAILS = 'DELETE_ORGER_DETAILS';